[package]
name = "sgmenu"
version = "0.1.0"
authors = ["David McKinney <mckinney@subgraph.com>"]

[dependencies]
gio = "0.3.0"
glib = "0.4.1"
gdk = "0.7.0"
pty = "0.2"
getopts = "0.2.17"
log = "0.4.0"
env_logger = "0.5.3"
